### ISSUE TITLE
Use a range of population sizes in power and validity analysis

### ISSUE THREAD

**Issue by BenjaminDalziel** [rachaelaber/2023_paper#1]
Currently it uses a fixed population size. We should examine power and validity at a range of population sizes

**Comment by BenjaminDalziel** [comment]
Since a primary feature of the method proposed is that it is not affected by population size, maybe it would be good to have a graph where population size was on the horizontal axis and p-values were on the y axis, with the points showing results for different magnitudes of theta1-theta2, or with separate panels for a few distinct theta1-theta2 levels.

**Comment by rachaelaber** [comment]
I added a variable to the curve_parms dataframe in generate_time_series.R to address (1).
