### ISSUE TITLE
Use a 2-side test?

### ISSUE THREAD

**Issue by BenjaminDalziel** [rachaelaber/2023_paper#15]
It seems like theta2 is frequently higher than theta1 so a 2-sided test seems appropriate.  Need to update the W() function in W.R? Need to rerun lrt_counties and Wald_counties?

**Comment by rachaelaber** [comment]
Right now it is a two-sided test - I'm assuming you mean change it to a one-sided test of theta2 - theta1 = 0 against the upper alternative that theta_2 - theta_1 > 0?

**Comment by BenjaminDalziel** [comment]
No, if it's 2-sided now that's great!
