### ISSUE TITLE
Is diff() working as intended in create_surfaces.R?

### ISSUE THREAD

**Issue by BenjaminDalziel** [rachaelaber/2023_paper#30]
Currently line 48:

lthetadiffs <- diff(lthetas)

Is this differencing along the correct dimension of the array? What happens when it gets to the end of a row or column?

One check would be to reconstruct a new version of lthetas, say "lthetas_check" by a cumulative sum of the lthetadiffs plus the initial value of ltheta. Does lthetas_check = ltheta?

**Comment by rachaelaber** [comment]
Whoops, forgot a transpose in there, thanks for catching that! 
When it gets to the end of a column, it "starts over" on the next column. I've added a picture here to illustrate what was originally happening v. the change that I made.

<img width="210" alt="Screen Shot 2024-01-15 at 7 12 27 PM" src="https://github.com/rachaelaber/2023_paper/assets/57012430/c6b01003-0b85-42ec-9211-a3b7bfb1a616">
