### ISSUE TITLE
Counties with all zeroes in the timeframe

### ISSUE THREAD

**Issue by rachaelaber** [rachaelaber/2023_paper#4]
How should we handle counties that have zero incidence in the time window of interest around Thanksgiving 2020? Right now, process_COVID_data.R removes rows which are all zero from the subset dataframe.

**Comment by BenjaminDalziel** [comment]
How about we just drop those counties from that analysis?

**Comment by BenjaminDalziel** [comment]
TODO: confirm and remark on this in the paper
