### ISSUE TITLE
Focus mostly on population-level heterogeneity in the intro

### ISSUE THREAD

**Issue by BenjaminDalziel** [rachaelaber/2023_paper#6]
Something to come back to later, and an "easy fix" I think: 

The introduction seems to switch back and forth between talking about individual and population-level variation. While we know they are importantly linked I think it might work better for this paper if the dominant focus stayed with population-level variation in the intro, because that is what the paper is mostly about. You could still mention individual-level variation, for instance in terms of its role in generating population-level dispersion. But there are sections of the intro now that seem to be talking about detecting and leveraging individual-level variation, e.g. "implementing targeted control strategies" that currently seem a bit confusing/out of place. 

I think some light editing will fix this - it's not like huge sections need to be removed. We can do this later.

**Comment by BenjaminDalziel** [comment]
Maybe another way to say this. When talking about individual-level variation in transmission potential: the main thing is to show how it links to population-level dispersion, and how estimating changes in dispersion may give better insights into patterns of individual-level variation (which we know are potentially important for control etc.)

**Comment by rachaelaber** [comment]
Sounds good. I think I'll include the Wegehaupt paper in Chapter 2 instead? :)

**Comment by rachaelaber** [comment]
I refocused the intro. Still need to add some background about population-level variability.
