### ISSUE TITLE
Specific aim section in Intro is out of date

### ISSUE THREAD

**Issue by BenjaminDalziel** [rachaelaber/2023_paper#8]
It says New York but we'll do every county we can, right?

Also, "specific aim" is more for grant proposals - work that has not yet been done. I think it might work just to remove the label and let what follows be the last paragraph of the intro

**Comment by rachaelaber** [comment]
Initially I used Florida and New York, but there's no reason not to do every US county.

**Comment by rachaelaber** [comment]
I removed the "specific aim" label and edited lrt_counties.R and wald_counties.R to include all US counties.
