### ISSUE TITLE
Thinking about figure flow in the paper

### ISSUE THREAD

**Issue by BenjaminDalziel** [rachaelaber/2023_paper#9]
I think a good thing to do next might be to finalize the figures and their legends. Then the results. The intro and methods are already in pretty good shape.

Wisdom from my advisor Steve Ellner -  "Figure 1 should have data in it". I think the idea is it is good to "set the stage" for what the paper is about with something important that exists in the world.

Figure 1. What about starting with something based on current Figure 3 (which is great!), show and example of increased dispersion following thanksgiving. (I wonder if this could be made more powerful with a counterfactual beside it, such as showing a simulation of the same time series but where dispersion did not increase)

Figure 2A Power and validity results for simulated data.
Figure 2B Mapping the thanksgiving hypothesis across the US - maybe mapping theta2-theta1?

Figure 3. Scanning for breakpoints

**Comment by BenjaminDalziel** [comment]
Anything else we need to show in figures could go in an appendix / supplemental.

**Comment by rachaelaber** [comment]
I added the suggested figure flow and created PDF's of all figures (including those for supplemental). Map figure needs more work.
